CREATE TABLE `ojha_user`.`user_profile` (
  `USR_ID` INT NOT NULL AUTO_INCREMENT,
  `USR_NME` VARCHAR(45) NOT NULL,
  `USR_PWD` VARCHAR(15) NOT NULL,
  `FRST_NME` VARCHAR(30) NOT NULL,
  `LST_NME` VARCHAR(30) NOT NULL,
  `USR_ADDR` VARCHAR(120) NULL,
  `USR_CTY` VARCHAR(45) NULL,
  `USR_STE` VARCHAR(45) NULL,
  `USR_CNTRY` VARCHAR(45) NULL,
  `USR_PIN` INT(6) NULL,
  `USR_PHN` INT(10) NULL,
  `USR_MAIL_ID` VARCHAR(45) NOT NULL,
  `CRT_TMS` DATETIME NOT NULL,
  `UPDT_TMS` DATETIME NULL,
  PRIMARY KEY (`USR_ID`),
  UNIQUE INDEX `USR_ID_UNIQUE` (`USR_ID` ASC) VISIBLE,
  UNIQUE INDEX `USR_NME_UNIQUE` (`USR_NME` ASC) VISIBLE,
  UNIQUE INDEX `USR_MAIL_ID_UNIQUE` (`USR_MAIL_ID` ASC) VISIBLE,
  UNIQUE INDEX `USR_PHN_UNIQUE` (`USR_PHN` ASC) VISIBLE);
  
  CREATE TABLE `ojha_user`.`user_roles` (
  `USR_RLE_ID` INT NOT NULL AUTO_INCREMENT,
  `USR_ID` INT NOT NULL,
  `RLE_ID` INT NOT NULL,
  PRIMARY KEY (`USR_RLE_ID`),
  UNIQUE INDEX `USR_RLE_ID_UNIQUE` (`USR_RLE_ID` ASC) VISIBLE,
  INDEX `USR_ID_idx` (`USR_ID` ASC) VISIBLE,
  INDEX `RLE_ID_idx` (`RLE_ID` ASC) VISIBLE,
  CONSTRAINT `USR_ID`
    FOREIGN KEY (`USR_ID`)
    REFERENCES `ojha_user`.`user_profile` (`USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RLE_ID`
    FOREIGN KEY (`RLE_ID`)
    REFERENCES `ojha_user`.`role_details` (`RLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
  
  
CREATE TABLE `ojha_user`.`role_details` (
  `RLE_ID` int NOT NULL AUTO_INCREMENT,
  `RLE_NME` varchar(10) NOT NULL,
  PRIMARY KEY (`RLE_ID`),
  UNIQUE KEY `RLE_ID_UNIQUE` (`RLE_ID`),
  UNIQUE KEY `RLE_NME_UNIQUE` (`RLE_NME`)
); 